/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestSwingApplication0;

import TestSwingApplication0.connectivity.DBConnector;
import java.sql.Connection;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


/**
 *
 * @author INDIA
 */
public class NewDetailPage extends javax.swing.JFrame {
    Connection con= null;
        Statement st= null;
        ResultSet rs= null;
        
        /*
     * Creates new form NewDetailPage
     */
    public NewDetailPage() {
        initComponents();
       
         st = DBConnector.getStatement();
         
          
    }
    public NewDetailPage(String email) {
        initComponents();
        welcome2.setText("welcome "+email+"...!");
        
                try
          {
             st = DBConnector.getStatement();          
              String query = "SELECT * FROM emp WHERE empmailid='"+email+"'";
              System.out.println("Query ="+query);
              
              rs =st.executeQuery(query);
              if(rs.next())
                      {
                          String id = rs.getString("empid");
                  String usernam = rs.getString("empname");
                  String  lastnam = rs.getString("emplastname");
                  String  Department = rs.getString("empDepartment");
                  String  working = rs.getString("empWorking");
                  String address1 = rs.getString("empaddress");
                  String address3 = rs.getString("empaddress2");
                  String salary = rs.getString("empsalary");
                  String city1 = rs.getString("empcity");
                  String state1 = rs.getString("empstate");
                  String sex = rs.getString("empsex");
                  String zipcode1 = rs.getString("empzipcode");
                  String phoneNo = rs.getString("emphoneno");
                  usernameId.setText(id+"..!");
                  usernameLabel1.setText(usernam+"..!");
                  lastnameLabel1.setText(lastnam+"..!");
                  mailidlabel1.setText(email+"..!");
                  departmentLabel1.setText(Department+"..!");
                  batchLabel1.setText(working+"..!");
                  addressLabel1.setText(address1+"..!");
                  addressLabel2.setText(address3+"..!");
                  salaryLabel2.setText(salary+"..!");
                  cityLabel1.setText(city1+"..!");
                  stateLabel1.setText(state1+"..!");
                  genderLabel1.setText(sex+"..!");
                  zipcodeLabel1.setText(zipcode1+"..!");
                  phoneNoLabel.setText(phoneNo+"..!");
                      }
              else{
                 errorLabel1.setVisible(true);
              }
          }
          catch(SQLException ex)
          {
              System.out.println(ex);
          }
         
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        signOutButton1 = new javax.swing.JButton();
        welcome2 = new javax.swing.JLabel();
        departmentLabel1 = new javax.swing.JLabel();
        batchLabel1 = new javax.swing.JLabel();
        addressLabel2 = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();
        salaryLabel2 = new javax.swing.JLabel();
        cityLabel1 = new javax.swing.JLabel();
        stateLabel1 = new javax.swing.JLabel();
        genderLabel1 = new javax.swing.JLabel();
        zipcodeLabel1 = new javax.swing.JLabel();
        errorLabel1 = new javax.swing.JLabel();
        usernameId = new javax.swing.JLabel();
        usernameLabel1 = new javax.swing.JLabel();
        lastnameLabel1 = new javax.swing.JLabel();
        mailidlabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        phoneNoLabel = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)), "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Last Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Mail ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Employee ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Department");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Batch");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Additional Address");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Salary");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("City");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("State");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Gender");

        jLabel13.setText("Zip Code");

        signOutButton1.setBackground(new java.awt.Color(51, 51, 255));
        signOutButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signOutButton1.setForeground(new java.awt.Color(255, 255, 255));
        signOutButton1.setText("Sign Out");
        signOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButton1ActionPerformed(evt);
            }
        });

        welcome2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        welcome2.setText("Welcome @Email ...! ");

        departmentLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        departmentLabel1.setForeground(new java.awt.Color(51, 51, 255));
        departmentLabel1.setText("Departmant..!");

        batchLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        batchLabel1.setForeground(new java.awt.Color(51, 51, 255));
        batchLabel1.setText("batch..!");

        addressLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressLabel2.setForeground(new java.awt.Color(51, 51, 255));
        addressLabel2.setText("additionaladdress..!");

        addressLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressLabel1.setForeground(new java.awt.Color(51, 51, 255));
        addressLabel1.setText("address..!");

        salaryLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        salaryLabel2.setForeground(new java.awt.Color(51, 51, 255));
        salaryLabel2.setText("salary..!");

        cityLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cityLabel1.setForeground(new java.awt.Color(51, 51, 255));
        cityLabel1.setText("city..!");

        stateLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stateLabel1.setForeground(new java.awt.Color(51, 51, 255));
        stateLabel1.setText("state..!");

        genderLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        genderLabel1.setForeground(new java.awt.Color(51, 51, 255));
        genderLabel1.setText("gender..!");

        zipcodeLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zipcodeLabel1.setForeground(new java.awt.Color(102, 102, 255));
        zipcodeLabel1.setText("zipcode..!");

        errorLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        errorLabel1.setForeground(new java.awt.Color(255, 51, 51));
        errorLabel1.setText("Due to some resons your data is not visible");

        usernameId.setForeground(new java.awt.Color(51, 51, 255));
        usernameId.setText("usernameid..!");

        usernameLabel1.setForeground(new java.awt.Color(51, 51, 255));
        usernameLabel1.setText("Username..!");

        lastnameLabel1.setForeground(new java.awt.Color(51, 51, 255));
        lastnameLabel1.setText("lastname..!");

        mailidlabel1.setForeground(new java.awt.Color(51, 51, 255));
        mailidlabel1.setText("mailid..!");

        jLabel16.setText("Phone No");

        phoneNoLabel.setForeground(new java.awt.Color(51, 51, 255));
        phoneNoLabel.setText("phoneNo..!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(63, 63, 63)
                        .addComponent(addressLabel2))
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)
                        .addComponent(departmentLabel1))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(welcome2)
                    .addComponent(errorLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(batchLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addressLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cityLabel1)
                                        .addComponent(salaryLabel2)
                                        .addComponent(stateLabel1)
                                        .addComponent(genderLabel1)
                                        .addComponent(zipcodeLabel1)))
                                .addGap(232, 232, 232)
                                .addComponent(signOutButton1))
                            .addComponent(usernameId)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLabel1)
                                    .addComponent(mailidlabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(30, 30, 30)
                                        .addComponent(lastnameLabel1)
                                        .addGap(48, 48, 48))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(48, 48, 48)
                                        .addComponent(phoneNoLabel)
                                        .addGap(63, 63, 63)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(welcome2)
                .addGap(37, 37, 37)
                .addComponent(errorLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(usernameId))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(usernameLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lastnameLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mailidlabel1)
                            .addComponent(jLabel16)
                            .addComponent(phoneNoLabel))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(departmentLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(batchLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(addressLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(addressLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(salaryLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cityLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(stateLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(genderLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(zipcodeLabel1))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButton1ActionPerformed
       HomePageNo0 hp0 = new HomePageNo0();
       hp0.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signOutButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewDetailPage().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JLabel addressLabel2;
    private javax.swing.JLabel batchLabel1;
    private javax.swing.JLabel cityLabel1;
    private javax.swing.JLabel departmentLabel1;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastnameLabel1;
    private javax.swing.JLabel mailidlabel1;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JLabel salaryLabel2;
    private javax.swing.JButton signOutButton1;
    private javax.swing.JLabel stateLabel1;
    private javax.swing.JLabel usernameId;
    private javax.swing.JLabel usernameLabel1;
    private javax.swing.JLabel welcome2;
    private javax.swing.JLabel zipcodeLabel1;
    // End of variables declaration//GEN-END:variables
}
