/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testswingapplication25;

import java.awt.Color;

/**
 *
 * @author INDIA
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        upperPanel = new javax.swing.JPanel();
        username1 = new javax.swing.JLabel();
        password1 = new javax.swing.JLabel();
        usernameField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginPage1 = new javax.swing.JLabel();
        sumbitButton1 = new javax.swing.JButton();
        resetButton1 = new javax.swing.JButton();
        lowerPanel = new javax.swing.JPanel();
        submitButton2 = new javax.swing.JButton();
        ExitButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        upperPanel.setBackground(new java.awt.Color(102, 255, 255));
        upperPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UpperPanel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        upperPanel.setToolTipText("THIS IS UPPER PANNEL");
        upperPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upperPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upperPanelMouseExited(evt);
            }
        });

        username1.setBackground(new java.awt.Color(255, 0, 102));
        username1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        username1.setForeground(new java.awt.Color(0, 0, 51));
        username1.setText("USERNAME:-");

        password1.setBackground(new java.awt.Color(255, 0, 102));
        password1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        password1.setForeground(new java.awt.Color(0, 0, 51));
        password1.setText("PASSWORD:-");

        usernameField1.setBackground(new java.awt.Color(204, 204, 204));
        usernameField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usernameField1.setText("jTextField1");
        usernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameField1ActionPerformed(evt);
            }
        });

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        loginPage1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        loginPage1.setForeground(new java.awt.Color(255, 0, 0));
        loginPage1.setText("LOGIN PAGE");

        sumbitButton1.setBackground(new java.awt.Color(255, 255, 255));
        sumbitButton1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        sumbitButton1.setForeground(new java.awt.Color(0, 0, 51));
        sumbitButton1.setText("SUMBIT");
        sumbitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbitButton1ActionPerformed(evt);
            }
        });

        resetButton1.setBackground(new java.awt.Color(255, 255, 255));
        resetButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        resetButton1.setText("RESET");
        resetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(loginPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addComponent(username1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sumbitButton1)
                        .addGap(38, 38, 38))
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addComponent(password1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(upperPanelLayout.createSequentialGroup()
                                .addComponent(resetButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))))
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(loginPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(sumbitButton1)
                .addContainerGap())
        );

        lowerPanel.setBackground(new java.awt.Color(204, 204, 255));
        lowerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LowerPanel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        lowerPanel.setToolTipText("THIS IS LOWER PANEL");
        lowerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lowerPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lowerPanelMouseExited(evt);
            }
        });

        submitButton2.setBackground(new java.awt.Color(255, 255, 255));
        submitButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        submitButton2.setText("SUBMIT");

        ExitButton1.setBackground(new java.awt.Color(255, 51, 51));
        ExitButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ExitButton1.setForeground(new java.awt.Color(255, 0, 51));
        ExitButton1.setText("EXIT");
        ExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lowerPanelLayout = new javax.swing.GroupLayout(lowerPanel);
        lowerPanel.setLayout(lowerPanelLayout);
        lowerPanelLayout.setHorizontalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerPanelLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExitButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        lowerPanelLayout.setVerticalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ExitButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(submitButton2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable(){
        public void run(){
            new NewJPanel().setVisible(true);
        }
    });
    }
    private void upperPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upperPanelMouseEntered
       upperPanel.setBackground(Color.RED);
    }//GEN-LAST:event_upperPanelMouseEntered

    private void upperPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upperPanelMouseExited
        upperPanel.setBackground(Color.cyan);
    }//GEN-LAST:event_upperPanelMouseExited

    private void lowerPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowerPanelMouseEntered
        lowerPanel.setBackground(Color.green);
    }//GEN-LAST:event_lowerPanelMouseEntered

    private void lowerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowerPanelMouseExited
        lowerPanel.setBackground(Color.YELLOW);
    }//GEN-LAST:event_lowerPanelMouseExited

    private void usernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void sumbitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbitButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumbitButton1ActionPerformed

    private void resetButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButton1ActionPerformed

    private void ExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel loginPage1;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JLabel password1;
    private javax.swing.JButton resetButton1;
    private javax.swing.JButton submitButton2;
    private javax.swing.JButton sumbitButton1;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel username1;
    private javax.swing.JTextField usernameField1;
    // End of variables declaration//GEN-END:variables
}
